package com.networkmonitor.service;

import com.networkmonitor.entity.Device;
import com.networkmonitor.repository.DeviceRepository;
import org.slf4j.Logger;import org.slf4j.LoggerFactory;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;
import java.time.LocalDateTime;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicBoolean;

@Service public class MonitoringSchedulerService{
 private static final Logger log=LoggerFactory.getLogger(MonitoringSchedulerService.class); private final DeviceRepository repo;private final DeviceMonitoringService monitor;private final AtomicBoolean active=new AtomicBoolean(true),running=new AtomicBoolean(false);private final ExecutorService pool=Executors.newFixedThreadPool(10);private final Map<Long,Long> nextDue=new ConcurrentHashMap<>();private LocalDateTime lastRunTime;private long lastCycleDurationMs;private int lastDevicesScannedCount;
 public MonitoringSchedulerService(DeviceRepository r,DeviceMonitoringService m){repo=r;monitor=m;}
 @Scheduled(fixedDelayString="${monitoring.scheduler.interval:10000}") public void executeScheduledMonitoringCycle(){if(!active.get()||!running.compareAndSet(false,true))return;long start=System.currentTimeMillis();try{List<Device> ds=repo.findByMonitoringEnabledTrue();lastRunTime=LocalDateTime.now();int due=0;CountDownLatch latch=new CountDownLatch(ds.size());for(Device d:ds){long now=System.currentTimeMillis(), interval=Math.max(1,d.getScanInterval()==null?10:d.getScanInterval())*1000L;if(now>=nextDue.getOrDefault(d.getId(),0L)){due++;nextDue.put(d.getId(),now+interval);pool.submit(()->{try{monitor.performPingCheck(d.getId());}catch(Exception e){log.error("Monitoring failed for device {}",d.getId(),e);}finally{latch.countDown();}});}else latch.countDown();}latch.await(8,TimeUnit.SECONDS);lastDevicesScannedCount=due;lastCycleDurationMs=System.currentTimeMillis()-start;}catch(InterruptedException e){Thread.currentThread().interrupt();}finally{running.set(false);}}
 public boolean startScheduler(){active.set(true);return true;}public boolean stopScheduler(){active.set(false);return true;}public boolean isSchedulerActive(){return active.get();}public boolean isCycleRunning(){return running.get();}public LocalDateTime getLastRunTime(){return lastRunTime;}public long getLastCycleDurationMs(){return lastCycleDurationMs;}public int getLastDevicesScannedCount(){return lastDevicesScannedCount;}public int getWorkerPoolSize(){return 10;}
}