package com.networkmonitor.service;

import com.networkmonitor.dto.*;import com.networkmonitor.entity.*;import com.networkmonitor.repository.DeviceRepository;import com.networkmonitor.exception.ResourceNotFoundException;import jakarta.persistence.criteria.Predicate;import org.springframework.data.jpa.domain.Specification;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.LocalDateTime;import java.util.*;import java.util.stream.Collectors;
@Service public class DeviceService { private final DeviceRepository repo; public DeviceService(DeviceRepository repo){this.repo=repo;}
@Transactional(readOnly=true) public List<DeviceResponseDto> getAllDevices(String search,DeviceType type,DeviceStatus status){Specification<Device>s=(r,q,c)->{List<Predicate>p=new ArrayList<>();if(type!=null)p.add(c.equal(r.get("deviceType"),type));if(status!=null)p.add(c.equal(r.get("status"),status));if(search!=null&&!search.trim().isEmpty()){String x="%"+search.trim().toLowerCase()+"%";p.add(c.or(c.like(c.lower(r.get("name")),x),c.like(r.get("ipAddress"),x),c.like(c.lower(r.get("hostname")),x)));}return c.and(p.toArray(new Predicate[0]));};return repo.findAll(s).stream().map(DeviceResponseDto::fromEntity).collect(Collectors.toList());}
@Transactional(readOnly=true) public DeviceResponseDto getDeviceById(Long id){return DeviceResponseDto.fromEntity(repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Device not found with id: "+id)));}
@Transactional public DeviceResponseDto createDevice(DeviceRequestDto x){validate(x);if(repo.existsByIpAddress(x.getIpAddress()))throw new IllegalArgumentException("Device with IP address '"+x.getIpAddress()+"' already exists.");Device d=new Device();map(x,d);return DeviceResponseDto.fromEntity(repo.save(d));}
@Transactional public DeviceResponseDto updateDevice(Long id,DeviceRequestDto x){validate(x);Device d=repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Device not found with id: "+id));if(!d.getIpAddress().equalsIgnoreCase(x.getIpAddress())&&repo.existsByIpAddress(x.getIpAddress()))throw new IllegalArgumentException("Device with IP address '"+x.getIpAddress()+"' already exists.");map(x,d);return DeviceResponseDto.fromEntity(repo.save(d));}
@Transactional public DeviceResponseDto upsertDiscoveredDevice(DiscoveredDeviceDto x){Device d=repo.findByIpAddress(x.getIpAddress()).orElseGet(Device::new);boolean created=d.getId()==null;if(created){d.setIpAddress(x.getIpAddress());d.setName(x.getSuggestedName()!=null?x.getSuggestedName():x.getIpAddress());d.setDeviceType(x.getSuggestedType()!=null?x.getSuggestedType():DeviceType.WORKSTATION);d.setMonitoringEnabled(true);d.setScanInterval(10);}if(x.getHostname()!=null&&!x.getHostname().equals(x.getIpAddress()))d.setHostname(x.getHostname());if(x.getSuggestedType()!=null)d.setDeviceType(x.getSuggestedType());if(x.getMacAddress()!=null)d.setMacAddress(x.getMacAddress());if(x.getVendor()!=null&&!x.getVendor().equals("Unknown"))d.setVendor(x.getVendor());if(x.getOsClue()!=null)d.setOsClue(x.getOsClue());d.setStatus(DeviceStatus.ONLINE);d.setLastSeenAt(LocalDateTime.now());return DeviceResponseDto.fromEntity(repo.save(d));}
@Transactional public DeviceResponseDto toggleMonitoring(Long id){Device d=repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Device not found with id: "+id));d.setMonitoringEnabled(!d.isMonitoringEnabled());return DeviceResponseDto.fromEntity(repo.save(d));}@Transactional public void deleteDevice(Long id){if(!repo.existsById(id))throw new ResourceNotFoundException("Device not found with id: "+id);repo.deleteById(id);}
private void validate(DeviceRequestDto x){if(x.getName()==null||x.getName().trim().isEmpty())throw new IllegalArgumentException("Device name cannot be empty.");if(x.getIpAddress()==null||!validIp(x.getIpAddress()))throw new IllegalArgumentException("Invalid IP address: "+x.getIpAddress());if(x.getDeviceType()==null)throw new IllegalArgumentException("Device type is required.");if(x.getScanInterval()!=null&&x.getScanInterval()<=0)throw new IllegalArgumentException("Scan interval must be positive.");}private boolean validIp(String ip){try{String[]p=ip.split("\\.");if(p.length!=4)return false;for(String s:p){int v=Integer.parseInt(s);if(v<0||v>255)return false;}return true;}catch(Exception e){return false;}}private void map(DeviceRequestDto x,Device d){d.setName(x.getName().trim());d.setIpAddress(x.getIpAddress().trim());d.setHostname(x.getHostname()!=null?x.getHostname().trim():null);d.setDeviceType(x.getDeviceType());d.setVendor(x.getVendor());d.setModel(x.getModel());d.setMacAddress(x.getMacAddress());d.setOsClue(x.getOsClue());if(x.getMonitoringEnabled()!=null)d.setMonitoringEnabled(x.getMonitoringEnabled());if(x.getScanInterval()!=null)d.setScanInterval(x.getScanInterval());}}
