package com.networkmonitor.controller;

import com.networkmonitor.dto.*;import com.networkmonitor.entity.Device;import com.networkmonitor.exception.ResourceNotFoundException;import com.networkmonitor.monitoring.NmapService;import com.networkmonitor.monitoring.SnmpService;import com.networkmonitor.repository.DeviceEventRepository;import com.networkmonitor.repository.DeviceRepository;import com.networkmonitor.service.DeviceMonitoringService;import org.springframework.http.ResponseEntity;import org.springframework.web.bind.annotation.*;import java.util.List;import java.util.stream.Collectors;
@RestController @RequestMapping("/api/devices") public class MonitoringController{
 private final DeviceMonitoringService monitoringService;private final DeviceRepository deviceRepository;private final NmapService nmapService;private final SnmpService snmpService;private final DeviceEventRepository eventRepository;
 public MonitoringController(DeviceMonitoringService m,DeviceRepository d,NmapService n,SnmpService s,DeviceEventRepository e){monitoringService=m;deviceRepository=d;nmapService=n;snmpService=s;eventRepository=e;}
 @PostMapping("/{id}/check") public ResponseEntity<PingCheckResponseDto> check(@PathVariable Long id){return ResponseEntity.ok(monitoringService.performPingCheck(id));}
 @GetMapping("/{id}/metrics") public ResponseEntity<List<MetricResponseDto>> metrics(@PathVariable Long id){return ResponseEntity.ok(monitoringService.getDeviceMetrics(id));}
 @GetMapping("/{id}/events") public ResponseEntity<List<DeviceEventDto>> events(@PathVariable Long id){if(!deviceRepository.existsById(id))throw new ResourceNotFoundException("Device not found with id: "+id);return ResponseEntity.ok(eventRepository.findTop100ByDeviceIdOrderByEventTimeDesc(id).stream().map(DeviceEventDto::from).collect(Collectors.toList()));}
 @PostMapping("/{id}/scan-ports") public ResponseEntity<PortScanResponseDto> ports(@PathVariable Long id){return ResponseEntity.ok(monitoringService.performPortScan(id));}
 @GetMapping("/{id}/ports") public ResponseEntity<List<PortStatusDto>> getPorts(@PathVariable Long id){return ResponseEntity.ok(monitoringService.getDevicePorts(id));}
 @PostMapping("/{id}/nmap-scan") public ResponseEntity<NmapScanResultDto> nmap(@PathVariable Long id,@RequestParam(required=false,defaultValue="FAST_PORT") String profile){Device d=deviceRepository.findById(id).orElseThrow(()->new ResourceNotFoundException("Device not found with id: "+id));return ResponseEntity.ok(nmapService.scanTarget(d.getIpAddress(),profile));}
 @PostMapping("/{id}/snmp-check") public ResponseEntity<SnmpMetricDto> snmp(@PathVariable Long id,@RequestParam(required=false,defaultValue="public") String community){Device d=deviceRepository.findById(id).orElseThrow(()->new ResourceNotFoundException("Device not found with id: "+id));return ResponseEntity.ok(snmpService.querySnmpMetrics(d.getId(),d.getIpAddress(),community));}
 @GetMapping("/{id}/snmp") public ResponseEntity<SnmpMetricDto> getSnmp(@PathVariable Long id){Device d=deviceRepository.findById(id).orElseThrow(()->new ResourceNotFoundException("Device not found with id: "+id));return ResponseEntity.ok(snmpService.querySnmpMetrics(d.getId(),d.getIpAddress(),"public"));}
}